version: '3'

services:

  #PHP Service
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    volumes:
      - ./:/var/www/html
      - ./docker-files/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    ports:
      - "9000:9000"
    networks:
      - laravel

  #Nginx Service
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./docker-files/nginx/default.conf/:/etc/nginx/conf.d/default.conf
    networks:
      - laravel

  #MySQL Service
  mysql:
    image: mysql:5.7.22
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - "4306:3306"
    environment:
      MYSQL_DATABASE: online_course
      MYSQL_ROOT_PASSWORD: 123456
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-files/mysql:/var/lib/mysql
    networks:
      - laravel
#Docker Networks
networks:
  laravel:
    driver: bridge
#Volumes
volumes:
  dbdata:
    driver: local

